### ISSUE TITLE
Memory leak when Telegram server close the connection

### ISSUE THREAD

**Issue by arduino12** [cotestatnt/CTBot#10]
**Hi,**

This issue report started as a comment **[here](https://github.com/cotestatnt/AsyncTelegram/commit/cb905181b262db708094782547467461f1a0dd03#r45931176)** :)

I just flashed the [dev](https://github.com/cotestatnt/AsyncTelegram/tree/dev) branch to my ESP32,
I will leave it to run in debug mode and capture its log to a file - I will report if the problem occurs.

From a 5 minutes test, the memory seems stable with:
`Heap: 176092, MaxFree: 113792, Task stack: 6576`

Thanks for all the great work on the dev branch!
Arad.

**Comment by arduino12** [comment]
Hi @cotestatnt ,

The setup with the [dev](https://github.com/cotestatnt/AsyncTelegram/tree/dev) branch  lasted OK for ~12 hours,

Then I got:

![image](https://user-images.githubusercontent.com/11454280/105699230-b1f98500-5f0f-11eb-83aa-cddecd4046fe.png)

And:

![image](https://user-images.githubusercontent.com/11454280/105699298-c9387280-5f0f-11eb-9ba2-3be2ced2dddb.png)

I don't understand why is shows:
`[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 5 - STA_DISCONNECTED`
Because the setup is near my router..
It worked well from the same spot for the first ~12H and then stopped..

I will keep testing and report here!

**Comment by cotestatnt** [comment]
Thanks for your preciuos feedback @arduino12 !
I've experienced the same behaviour, and it seems related to _telegramClient.setCACert(digicert);_ instruction.
Infact, while with ESP8266 seems to be necessary set again the certficate in order to connect (otherwise it fails), with ESP32 it is not necessary, indeed it makes the situation worse. This made me confusing.

Try to remove all instructions related to ESP32 in checkConnection() method or sync with last commit https://github.com/cotestatnt/AsyncTelegram/commit/a8d3f2a6389a75b2d9f31123402a67b2c1abdf43

**Comment by cotestatnt** [comment]
Problem still present :( 
The thing I can't explain is that I have problems only with ESP32-CAM breakout board.
With a NodeMCU-32S it runs like a charm.

**Comment by arduino12** [comment]
Indeed very weird..!

I made the previous test with my `ESP32-DEVKITV1` (because I got brownout errors with my `ESP32-CAM` with the new code)
I restarted it 11 hours ago - and so far it works OK - the ssl error did not occurred yet..

I will test with my `ESP32-CAM` once I see that the DEVKIT works fine because I trust the DEVKIT more.

About our `ESP32-CAM`:
Maybe the problem is related to the fact that it have PSRAM?
Or that it uses the ESP32-S (the S is for single core - not dual core like other common ESP32 boards)?
Please see the table in the middle of **[this](https://maker.pro/esp8266/tutorial/a-comparison-of-the-new-esp32-s2-to-the-esp32)** page.

About the `setCACert`, maybe we can try skipping the security verification (fingerprint and digicert),
Just to tell if the problem is related to them or not?

**Comment by mandgeo** [comment]
I'm facing the same issue, only i don't have the way to give such logs. The main idea is that the telegram bot (the one managed by the sketch) dies after certain time. Is there any workaround for this problem? Maybe calling begin from time to time, but when? In keywords.txt i can see testConnection, but not in the source. In the source files there is checkConnection, but i think is for the source private use. I get "within this context" error. 
I'm using ESP32.
Excuse me if I seem to be confused. I'm not a programmer.

**Comment by cotestatnt** [comment]
hello @mandgeo, sorry for late reply.
I'm still investigating on this issue (i haven't had much time unfortunately in the last few days).
The problem seems occur when Telegram server stop connection from it's side and in the headers you can find "Connection: close".

For the moment, i've found a workaround that seems work quite well. In few words when there is the string "Connection: close" in the headers, a manual reset of the connection will be forced.
Furthermore, I constantly check the amount of free memory associated with the esp32 task that manages the communication and when a memeory leak occurs, the task is deleted (which frees up the memory) and reinitialized.

If want to try it, check the dev branch where i've just uploaded the last changes.
Most likely you will have to make some small changes because many things have changed compared to the master version.
Take a look at the new examples included.

**Comment by gnalbandian** [comment]
Hi. The same problem ocurrs with esp8266.
When telegram closes the connections, and checkConnection() is called and tries to reconnect, the crash occurs because of Soft WDT.

I've narrowed the issues to this function:

```
bool WiFiClientSecure::_wait_for_handshake() {
  _handshake_done = false;
  while (!_handshake_done && _clientConnected()) {
    int ret = _run_until(BR_SSL_SENDAPP);
    if (ret < 0) {
      DEBUG_BSSL("_wait_for_handshake: failed\n");
      break;
    }
    if (br_ssl_engine_current_state(_eng) & BR_SSL_SENDAPP) {
      _handshake_done = true;
    }
    optimistic_yield(1000);
  }
  return _handshake_done;
}
```

**Comment by gnalbandian** [comment]
Yet, the only difference I found between the first connection flow, and the following reconnections aire the following function calls of the WiFiClient library:

int WiFiClient::connect(IPAddress ip, uint16_t port)
{
    if (_client) {
        stop();
        _client->unref();
        _client = nullptr;
    }
The function continues. But those 3 function calls are the only difference I could found.
Maybe there is some parameter, flag, or whatever that is not being cleared, or set accordingly to our needs.

**Comment by cotestatnt** [comment]
Hello to everyone.
With last ESP32 release and [this fix ](https://github.com/brokentoaster/arduino-esp32/pull/2/commits/9f5ab6609435e40629d02822c47e6f623fc31f00)(not included in release unluckily) problems related to memory leak seems solved.
I'm testing the dev branch since a couple days without unwanted reboots due to abnormal memory consumption.

Probably the fix is not in the "best" place because at the first connection attempt due to Telegram server connection close I get this error
_[E] [ssl_client.cpp: 36] _handle_error (): [start_ssl_client (): 221]: (-9984) X509 - Certificate verification failed, e.g. CRL, CA or signature check failed_.
The error then forces the clearing of buffers and after it goes as it should!

**Comment by arduino12** [comment]
Wow great job @cotestatnt !
I will test this fix as well (found [here](**url**) a bit more info).

PS:
I work with PlatformIO and just update my espressif32 platform to the newest [v3.1.0](https://github.com/platformio/platform-espressif32/releases),
And now it fails to start (restart loops):
```
...
Start http request task on core 0
[E][WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1
[E][WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
```

It is based on [ESP32 Arduino Release 1.0.5](https://github.com/espressif/arduino-esp32/releases/tag/1.0.5) so I hope they will fix it soon..
In the meantime we better use the previous version that seems to work OK (v3.0.0 but with the memory leak)..

Only conclusion is that the [`start_ssl_client`](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/src/ssl_client.cpp#L54-L260) function is cursed and hurt my eyes.. ;)

**Comment by cotestatnt** [comment]
Hi @arduino12. 
This is because with latest release now you have to esplicit call the setInsecure() method, otherwise connection fails and we get restart becase _AsyncTelegram::begin()_ try to parse an empty string.

For the moment i've added _telegramClient.setInsecure();_ instruction in last release (v1.1.1) and prevented an empty string from creating the exception, but i'm going to use the root certificates for the next one.

**Comment by arduino12** [comment]
Thanks for the quick fix @cotestatnt !

**So here are my test results:**
I update to [v1.1.1](https://github.com/cotestatnt/AsyncTelegram/releases/tag/1.1.1) and manually added the [memory leak fix](https://github.com/brokentoaster/arduino-esp32/pull/2/commits/9f5ab6609435e40629d02822c47e6f623fc31f00)-
Compiled with `DEBUG_MODE=1` and `CORE_DEBUG_LEVEL=5` and runs with my ESP-CAM board,
It seems that every 7 minutes I got the `Connection: close`-
first time the stack free memory went from `3684` to `3572`- and it remains the same after that..
But the reconnections were OK (I did not got the `X509 - Certificate verification failed` error you got)
**Sadly after 9 hours it stopped working - freeze, last log:**
```
[W][HTTPClient.cpp:1411] returnError(): error(-11): read Timeout
[D][HTTPClient.cpp:1413] returnError(): tcp stop
```
**But it still replies to ping sent from my PC - so I think the problem is only in the `AsyncTelegram` socket state machine.!**

Main logs:
```
WiFi connected: 192.168.1.106
Total space: 2032271360
Free space: 1899298816
```
...
```
[V][HTTPClient.cpp:239] beginInternal(): url: https://api.telegram.org/***/getUpdates
[D][HTTPClient.cpp:287] beginInternal(): host: api.telegram.org port: 443 url: /***/getUpdates
[D][HTTPClient.cpp:573] sendRequest(): request type: 'POST' redirCount: 0
[D][HTTPClient.cpp:1079] connect(): already connected, reusing connection
[V][ssl_client.cpp:306] send_ssl_data(): Writing HTTP request with 259 bytes...
[V][ssl_client.cpp:306] send_ssl_data(): Writing HTTP request with 85 bytes...
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'HTTP/1.1 200 OK'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Server: nginx/1.16.1'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Date: Sun, 28 Feb 2021 21:31:30 GMT'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Content-Type: application/json'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Content-Length: 23'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Connection: close'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Access-Control-Allow-Origin: *'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Access-Control-Allow-Methods: GET, POST, OPTIONS'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: ''
[D][HTTPClient.cpp:1251] handleHeaderResponse(): code: 200
[D][HTTPClient.cpp:1254] handleHeaderResponse(): size: 23
[D][HTTPClient.cpp:597] sendRequest(): sendRequest code=200
[D][HTTPClient.cpp:1388] writeToStreamDataBlock(): connection closed or file end (written: 23).
[D][HTTPClient.cpp:381] disconnect(): tcp stop
[V][ssl_client.cpp:276] stop_ssl_socket(): Cleaning SSL connection.
HTTPS payload: getNewMessage JSON: 
{"ok":true,"result":[]}
[D][HTTPClient.cpp:394] disconnect(): tcp is closed
Time: 3325, stack: 3684
```
...
```
[V][HTTPClient.cpp:239] beginInternal(): url: https://api.telegram.org/***/getUpdates
[D][HTTPClient.cpp:287] beginInternal(): host: api.telegram.org port: 443 url: /***/getUpdates
[D][HTTPClient.cpp:573] sendRequest(): request type: 'POST' redirCount: 0
[V][ssl_client.cpp:59] start_ssl_client(): Free internal heap before TLS 139092
[V][ssl_client.cpp:65] start_ssl_client(): Starting socket
[V][ssl_client.cpp:104] start_ssl_client(): Seeding the random number generator
[V][ssl_client.cpp:113] start_ssl_client(): Setting up the SSL/TLS structure...
[I][ssl_client.cpp:127] start_ssl_client(): WARNING: Skipping SSL Verification. INSECURE!
[V][ssl_client.cpp:197] start_ssl_client(): Setting hostname for TLS session...
[V][ssl_client.cpp:212] start_ssl_client(): Performing the SSL/TLS handshake...
[V][ssl_client.cpp:244] start_ssl_client(): Verifying peer X.509 certificate...
[V][ssl_client.cpp:253] start_ssl_client(): Certificate verified.
[V][ssl_client.cpp:268] start_ssl_client(): Free internal heap after TLS 93092
[D][HTTPClient.cpp:1119] connect():  connected to api.telegram.org:443
[V][ssl_client.cpp:306] send_ssl_data(): Writing HTTP request with 259 bytes...
[V][ssl_client.cpp:306] send_ssl_data(): Writing HTTP request with 85 bytes...
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'HTTP/1.1 200 OK'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Server: nginx/1.16.1'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Date: Sun, 28 Feb 2021 21:31:36 GMT'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Content-Type: application/json'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Content-Length: 23'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Connection: keep-alive'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Access-Control-Allow-Origin: *'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Access-Control-Allow-Methods: GET, POST, OPTIONS'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: ''
[D][HTTPClient.cpp:1251] handleHeaderResponse(): code: 200
[D][HTTPClient.cpp:1254] handleHeaderResponse(): size: 23
[D][HTTPClient.cpp:597] sendRequest(): sendRequest code=200
[D][HTTPClient.cpp:1388] writeToStreamDataBlock(): connection closed or file end (written: 23).
[D][HTTPClient.cpp:379] disconnect(): tcp keep open for reuse
HTTPS payload: getNewMessage JSON: 
{"ok":true,"result":[]}
[D][HTTPClient.cpp:379] disconnect(): tcp keep open for reuse
Time: 4031, stack: 3572

[V][HTTPClient.cpp:239] beginInternal(): url: https://api.telegram.org/***/getUpdates
[D][HTTPClient.cpp:287] beginInternal(): host: api.telegram.org port: 443 url: /***/getUpdates
[D][HTTPClient.cpp:573] sendRequest(): request type: 'POST' redirCount: 0
[D][HTTPClient.cpp:1079] connect(): already connected, reusing connection
[V][ssl_client.cpp:306] send_ssl_data(): Writing HTTP request with 259 bytes...
[V][ssl_client.cpp:306] send_ssl_data(): Writing HTTP request with 85 bytes...
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'HTTP/1.1 200 OK'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Server: nginx/1.16.1'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Date: Sun, 28 Feb 2021 21:31:40 GMT'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Content-Type: application/json'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Content-Length: 23'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Connection: keep-alive'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Access-Control-Allow-Origin: *'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Access-Control-Allow-Methods: GET, POST, OPTIONS'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: 'Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection'
[V][HTTPClient.cpp:1210] handleHeaderResponse(): RX: ''
[D][HTTPClient.cpp:1251] handleHeaderResponse(): code: 200
[D][HTTPClient.cpp:1254] handleHeaderResponse(): size: 23
[D][HTTPClient.cpp:597] sendRequest(): sendRequest code=200
[D][HTTPClient.cpp:1388] writeToStreamDataBlock(): connection closed or file end (written: 23).
[D][HTTPClient.cpp:379] disconnect(): tcp keep open for reuse
HTTPS payload: getNewMessage JSON: 
{"ok":true,"result":[]}
[D][HTTPClient.cpp:379] disconnect(): tcp keep open for reuse
Time: 3754, stack: 3572
```
...
```
[V][HTTPClient.cpp:239] beginInternal(): url: https://api.telegram.org/***/getUpdates
[D][HTTPClient.cpp:287] beginInternal(): host: api.telegram.org port: 443 url: /***/getUpdates
[D][HTTPClient.cpp:573] sendRequest(): request type: 'POST' redirCount: 0
[D][HTTPClient.cpp:1079] connect(): already connected, reusing connection
[V][ssl_client.cpp:306] send_ssl_data(): Writing HTTP request with 259 bytes...
[V][ssl_client.cpp:306] send_ssl_data(): Writing HTTP request with 85 bytes...
[D][HTTPClient.cpp:597] sendRequest(): sendRequest code=-11
[W][HTTPClient.cpp:1411] returnError(): error(-11): read Timeout
[D][HTTPClient.cpp:1413] returnError(): tcp stop
[V][ssl_client.cpp:276] stop_ssl_socket(): Cleaning SSL connection.
HTTPS error: read Timeout
[D][HTTPClient.cpp:394] disconnect(): tcp is closed
Time: 5057, stack: 3572
```
No more logs from here and the device is not responding...

**Comment by gnalbandian** [comment]
Is there a workaround for ESP8266?

I have tracked down the issue of WDT upto where the reconnection succeeds at http level, and starts the handshake of SSL. 
There is where WDT pops up and restart the device.

**Comment by gnalbandian** [comment]
With this debug flags activated, the device wont reconnect but it wont halt either:

`build_flags = -Wall -DDEBUG_ESP_CORE -DDEBUG_ESP_WIFI -DDEBUG_BSSL -DDEBUG_ESP_PORT=Serial`

**Comment by cotestatnt** [comment]
@gnalbandian I'm testing the last library version (just uploaded, v1.1.2), since 5 continuos days. 
For the moment with ESP8266 **I have not** encountered any unwanted reboots and bot continue to echo my messages each time I try. I'm quite confident issue is solved on this platform.

With ESP32 unfortunately sometimes occurs again (more or less once every 2/3 days). 
At the moment I am trying [this sketch](https://pastebin.com/xHFFWvei) with the 40Mhz flash frequency instead 80Mhz, because I have readed in Arduino-ESP32 issues, that this can sometimes solve unwanted "SW_CPU_RESET" reset reason wich i'm facing now with my boards.
The sketch send me a Telegram message with last reset reason, so I'm sure to catch all events even if not connected to a PC.

**Comment by cotestatnt** [comment]
After countless tests and attempts to "work around" the problem, for ESP32 I am seriously thinking of ditching the library included in the WiFiClientSecure core and switch to [https://github.com/OPEnSLab-OSU/SSLClient](https://github.com/OPEnSLab-OSU/SSLClient) (based on BearSSL).
I'm sorry to add an additional dependency to the library, but from the first tests I've done seems to work much, much better.
Moreover, with this new library could be possible extend the usage of AsyncTelegram even to other platforms or adapter (ex. Ethernet).
