### ISSUE TITLE
sendToUser

### ISSUE THREAD

**Issue by workpage2** [cotestatnt/CTBot#13]
I cannot use this construct:

    myBot.sendToUser(userid, "test");
How to use it correctly?
If I replace "test" with a variable of type string - Everything works.

**Comment by AndiP1234** [comment]
`void AsyncTelegram::sendToUser(const int32_t userid, String &message, String keyboard)`
you need a string variable, direct with "xxxxx" it´s not possible.

http://tutors.ics.uci.edu/index.php/tutor-resources/81-cpp-resources/122-cpp-ref-pointer-operators
