### ISSUE TITLE
sizeof is not valid for retrieving length of String or const char*

### ISSUE THREAD

**Issue by stevesch** [cotestatnt/CTBot#15]
Use of "sizeof" throughout code to check for string lengths is incorrect.
suggest as a replacement:

bool isEmptyString(const char* str) {
  return !str || !str[0];
}

bool isEmptyString(const String& str) {
  return (str.length() == 0);
}

**Comment by cotestatnt** [comment]
@stevesch you're absolutely right!
I've just fixed this errors in last release
