### ISSUE TITLE
Messages gets lost

### ISSUE THREAD

**Issue by mandgeo** [cotestatnt/CTBot#19]
Hello,
I'm having a little problem using the library you've made. I have a sketch that is doing a lot of serial reading, three devices at 2400 baud and one at 9600. Of course I have to wait for answer for every command i send to the devices. For that i'm using vTaskDelay (not delay).
In certain cases, the sketch has to send messages. Some of those messages gets lost. They don't arrive at all. 
The setUpdateTime was set at 2000 and I've changed it to 1000...same problem. I've tried to add a vTaskDelay after sendToUser...same problem. I'm using String variable to compose my message.

Do you have any advice for me? Thank you!

**Comment by cotestatnt** [comment]
@mandgeo, unfortunately the maximum polling rate don't depend directly on the AsyncTelegram library.
When the WiFiClientSecure instance starts connecting with Telegram server, it takes some time for HTTP handshaking. This time is unusually long with ESP32 (1/2 seconds).
Paradoxically, the less powerful ESP8266 takes less time in this phase thanks to the excellent BearSSL library.

If you haven't sill found a fixes, maybe could be an idea accumulating messages in a temporary variable and send them at a reasonable fixed interval.

**Comment by AlexCrane73** [comment]
> If you haven't sill found a fixes, maybe could be an idea accumulating messages in a temporary variable and send them at a reasonable fixed interval.

Hello,
How to know when an HTTP connection has been established to send a message.

**Comment by cotestatnt** [comment]
HTTP connection it's handled frome core library WiFiClientSecure.
