### ISSUE TITLE
Add custom sendMessage parameter (feat request)

### ISSUE THREAD

**Issue by alepac** [cotestatnt/CTBot#24]
Add the possibility to append some parameter to the telegram sendMessage method.

A method with a signature like this could be helpful: 
```
void sendMessage(const TBMessage &msg, const char* message, String booleanParameter = "", bool parameterValue);
```
The method could be even more generic using a linked list of a custom type and in the custom type we can specify the parameter name and value.

As an example I need to send a message without notification sound so I need to set the `disable_notification` parameter to true.

**Comment by cotestatnt** [comment]
Sorry for late reply.

I've added support for "no notification" messages.
Instead adding new methods to handling wich will be confusing as my opinion, i've added the _**disable_notification**_ option in the struct of message (TBMessage).

So if you want send a silent message you can do something like this:
`
msg.disable_notification = true;
myBot.sendMessage(msg, "this is a silent message");
`

Regarding the other parameter, i'm not entirely sure they would be that useful, in any case I consider the request for next releases.

**Comment by alepac** [comment]
> I've added support for "no notification" messages.
> Instead adding new methods to handling wich will be confusing as my opinion, i've added the _**disable_notification**_ option in the struct of message (TBMessage).

That's enough for my needs.
Thanks
