### ISSUE TITLE
Send message by User ID: backward compatibility issue on 1.0.9+

### ISSUE THREAD

**Issue by vlw** [cotestatnt/CTBot#26]
https://github.com/cotestatnt/AsyncTelegram/commit/9518b0307c89cd884e072fc76aa9dfca92f911b0#r47630731

Look here, I found reason and solution.

**Comment by cotestatnt** [comment]
Hello @vlw 
What do you think about something like this added to public methods in AsyncTelegram.h
`    
inline void sendTo(const TBMessage &msg, const String &message, ReplyKeyboard &keyboard){
   sendTo(msg.sender.id, message, keyboard.getJSON() );
}
`

**Comment by vlw** [comment]
Hello @cotestatnt 
Main issue is "old code now doesn't work without changes"
`msg.sender.id = some_user_id` was enough for send message to user
Now all users who uses manual message send should change `msg.sender.id = some_user_id` to `msg.chatId = some_user_id`. It is broken backward compatibility.

**Comment by cotestatnt** [comment]
Ok, now i've undestood better your issue and agree with you.
I'm testing proposed solution and then i will put online for keeping backward compatibility. For the same reason i'm going to re-add methods sendToUser and sendToGroup (but deprecated)

Thank you!
