### ISSUE TITLE
New release make code fail.

### ISSUE THREAD

**Issue by HackEduca** [cotestatnt/CTBot#30]
Dear Tolentino, 
first of all Congratulation for this amazing delevopment.

I would like your help, if is possible.
Since you release new version I can't get make code working.
Initially let's inform you my setup:
ESP8266 nodeMCU and Wemos D1
ESP8266 Core = 2.7.4
ArduinoJson version: 6.17.1
AsyncTelegram version 1.0.8 (with a small change as described below)

In order to have the version 1.0.8 working I have to increase the Buffer Size as indicated in the issue: https://github.com/cotestatnt/AsyncTelegram/issues/6
So, in my library I have:
`DynamicJsonDocument doc(BUFFER_BIG);`

---------
I have attached the code and also the library I am using, in order to keep same scenario.

[test_AsyncTelegram.zip](https://github.com/cotestatnt/AsyncTelegram/files/6097876/test_AsyncTelegram.zip)

---------
As soon as I update your library for last version, inline keyboard is not available anymore, even change the code as before.

To test:
You should inform your userId, because I have in this code is a function to validate the user who will interact with the bot.

`int userId[] = {2360873, 0, 0, 0, 0, 0}; //--> Should include your UserID ==> send message to @myidbot`

Thanks in Advance.

Edson

**Comment by HackEduca** [comment]
Hi, I did some more test and I found the following.
If I increase the buffe to 1024, as before:
`DynamicJsonDocument doc(BUFFER_BIG);`

Always After code is uploded, Telegram can't conect.
Checking the Serial port we have the following:

![image](https://user-images.githubusercontent.com/44639965/110301366-c2088800-7fd6-11eb-9342-7774c0cdfe19.png)

After a manual reset, the keybord is there.

Hoewever this error happened just twice - just mentioned because can be relevant to track.....

Thanks!

**Comment by cotestatnt** [comment]
Thank for your feedback and patience @HackEduca 
You pointed my attention on two different bugs, indeed
The first is related to WiFi connection: at [this point](https://github.com/cotestatnt/AsyncTelegram/blob/master/src/AsyncTelegram.cpp#L97) I assume that wifi is connected, but strangely immediatly after uploading new firmware, at the very beginning this is not true. Adding instruction WiFi.reconnect() seem solve the issue.

In relation to the keyboard problem, the size too small[ is this ](https://github.com/cotestatnt/AsyncTelegram/blob/master/src/AsyncTelegram.cpp#L450)(related only to keyboard json and not to the complete message). I've doubled it now.

![image](https://user-images.githubusercontent.com/27758688/110352628-6ff74f00-8036-11eb-8688-5c8b5ea7fe18.png)

**Comment by HackEduca** [comment]
Thanks a lot for your prompt reply!
Appreciate your effort to make it available.

Grazie

Edson
