### ISSUE TITLE
Thank you for your ESP-32 Cam example, now I can receive a photo in full resolution

### ISSUE THREAD

**Issue by FBMinis** [cotestatnt/CTBot#34]
My objective was to have the ESP-32 camera send me a photo to Telegram every 10min, from 6h00 to 20h. To save energy and have more control over time and alarms, I added a DS3231 to my project. With other libraries and uploading methods, it was either not possible to send full resolution photos or it would fail after a while. It is crucial to have a good wifi connection and for that I upgraded the antenna (I have 4 units and pcb antenna gave me poor range in all of them), but it's also important to have a good power supply (good filtering to prevent artifacts in photos and high current delivery capability to maintain wifi communication).

https://github.com/FBMinis/DS3231-Alarm-ESP32-Cam-Telegram-Bot

Thank you for your work.

**Comment by cotestatnt** [comment]
Thank you for your feedback, and also for the sketch 👍
