### ISSUE TITLE
sendToGroup is deprecated - what is the new method to send to group ?

### ISSUE THREAD

**Issue by saikek** [cotestatnt/CTBot#35]
Hi, 

Since `sendToGroup` is marked deprecated,
what is the new (or future) way to send messages to group? 

Thank you.

**Comment by zzuutt** [comment]
Hi,
to send a message to a group

```
TBMessage msgGroup;
msgGroup.chatId = idGroup;
myBot.sendMessage(msgGroup, contentTelegram);
```

**Comment by saikek** [comment]
Understood, thank you!
