### ISSUE TITLE
Channel_id?

### ISSUE THREAD

**Issue by fmarzocca** [cotestatnt/CTBot#39]
Isn't channel ID required?

**Comment by gnalbandian** [comment]
Hi. I believe you should al least give some more detail about your concern.

The data you need from telegram response is very application dependent. Me myself, I'm not using channel id at all.

**Comment by fmarzocca** [comment]
I am managing my devices through a group, as I need that at least 2 users can access and share the messages. The group has a chat_id. Currently I am using another Bot library and I am evaluating this one. Is it possible to send/receive to/from a group where the bot is part of?

**Comment by fmarzocca** [comment]
In other words: my bot is part of a group and I need that all users of the group can use it.

**Comment by gnalbandian** [comment]
You shouldn't have trouble using the chatId to send messages back to the group.
For your bot to to receive messages from the group, it should be added as a member.

**Comment by fmarzocca** [comment]
Yes. My bot is added as a member tobthe group, but when I send a message
tovthe group the bot doesn't receive it.
It only rrceives messages sent directly to it.

- Sent from my mobile phone. Sorry for typos -

Il Ven 16 Apr 2021, 16:22 Gonzalo ***@***.***> ha scritto:

**Comment by gnalbandian** [comment]
You should read Telegram Bot API Docs

> When added to a group, bots do not receive all messages by default (see Privacy mode).
[https://core.telegram.org/bots](Link)

**Comment by fmarzocca** [comment]
Gonzalo, it's 3 years that I am working with my bot and another library.
The group has been correctly setup and it is working. I would give
AsyncTelegram a chance, but it is not working in my group.


- Sent from my mobile phone. Sorry for typos -

Il Ven 16 Apr 2021, 18:12 Gonzalo ***@***.***> ha scritto:

**Comment by fmarzocca** [comment]
Yes, the chat is in Privacy mode. What is the syntax of sendMessage in this library to send messages to the chan_id of the group?

**Comment by gnalbandian** [comment]
`void AsyncTelegram::sendMessage(const TBMessage &msg, const char* message, String keyboard)`

So:

You can define a TBMessage and define its chatIdwith the chatId of your group.

I'm no fan of this part but pay attention to this:

`root["chat_id"] = msg.sender.id != 0 ? msg.sender.id : msg.chatId;`

FWIW, I have developed my own telegram library (yet not published) that has been based upon this one but has grown very much apart, so my answers are based on my memory from previous usage and reading at  the code.

**Comment by gnalbandian** [comment]
You should be able to also use:
`void AsyncTelegram::sendTo(const int32_t userid, String &message, String keyboard)`

**Comment by fmarzocca** [comment]
I tried setting msg.chatId before sending the message, but it is still
delivered to the bot itself and not into the group.


When will you publish your lib?

- Sent from my mobile phone. Sorry for typos -

**Comment by fmarzocca** [comment]
I am trying this (from lightBot example):

```
	TBMessage msg;

	// if there is an incoming message...
	if (myBot.getNewMessage(msg)) {
                 msg.chatId= -xxxxxxxxxx;
                // (also tried with msg.group.id)
		if (msg.text.equalsIgnoreCase("/LIGHT ON")) {      
			digitalWrite(LED, LOW);                           
			myBot.sendMessage(msg, "Light is now ON");        
		}
}
```

but it is not sending to the group.

**Comment by fmarzocca** [comment]
I have fixed this way (not elegant, but it works..)

```
	// if there is an incoming message...
	if (myBot.getNewMessage(msg)) {
        msg.sender.id = 0;
        msg.chatId = -xxxxxx;
		if (msg.text.equalsIgnoreCase("/LIGHT ON")) {      // if the received message is "LIGHT ON"...
			digitalWrite(LED, LOW);                           // turn on the LED (inverted logic!)
			myBot.sendMessage(msg, "Light is now ON");        // notify the sender
		}
```

**Comment by fmarzocca** [comment]
closing
