### ISSUE TITLE
Flush message queue?

### ISSUE THREAD

**Issue by fmarzocca** [cotestatnt/CTBot#40]
Among the commands I am sending to my telegram-controlled bot device, there is the `/reboot` to ask the device to restart. The problem is that as soon as the device returns ready, it will get another `/reboot` command and so on forever.

Is there a way to "flush" the message queue before rebooting the device (or upon starting)?

**Comment by droidprova** [comment]
Hi, check the OTA examples for ESP8266, what you ask you can do like this: 

`while (!myBot.getUpdates()) {
                  Serial.print(".");
                  delay(50);
                }
                ESP.restart();`

**Comment by fmarzocca** [comment]
Thanks
