### ISSUE TITLE
Callback query issue

### ISSUE THREAD

**Issue by arendhofmeyr** [cotestatnt/CTBot#46]
Callback queries do not work.  The reason is that m_inlineKeyboard is not set

Issue can be resolved by changing (in AsyncTelegram.h)

    inline void sendMessage(const TBMessage &msg, const char* message, InlineKeyboard &keyboard)
    {
        return sendMessage(msg, message, keyboard.getJSON());
    }

to

    inline void sendMessage(const TBMessage &msg, const char* message, InlineKeyboard &keyboard)
    {
        m_inlineKeyboard = keyboard;
        return sendMessage(msg, message, keyboard.getJSON());
    }

**Comment by cotestatnt** [comment]
Thanks!
I've fixed the issue as suggested.

Fell free to submit a pull request if you find some other bugs.
