### ISSUE TITLE
Reply Keyboard can have not more than 10 buttons

### ISSUE THREAD

**Issue by andoryu-kun** [cotestatnt/CTBot#6]
When I'm trying to add 11-th button to the Reply Keyboard, it stops sending messages.

In master/src/AsyncTelegram.cpp: void AsyncTelegram::sendMessage
It turned out that 512 is not enough:

    if (keyboard.length() != 0) {
        DynamicJsonDocument doc(512);
        deserializeJson(doc, keyboard);
        JsonObject myKeyb = doc.as<JsonObject>();
        root["reply_markup"] = myKeyb;
    }

If I change  DynamicJsonDocument doc(512); to  DynamicJsonDocument doc(1024); it works fine.
Maybe it should be changed to BUFFER_BIG, or 1024 is enough.
Have a good day.

**Comment by HackEduca** [comment]
Worked for me as well, thanks!

**Comment by cotestatnt** [comment]
Increased the size in release 1.0.9
